# Generated by Django 4.1.2 on 2022-11-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprelojes', '0002_producto_url_nueva_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_nueva_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
