# Generated by Django 4.1.2 on 2022-11-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprelojes', '0003_alter_producto_url_nueva_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='url_imagen',
        ),
    ]
