# Generated by Django 4.1.2 on 2022-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='cumpleanos',
            field=models.DateField(null=True),
        ),
    ]
